name: API Docker

on:
  pull_request:
    branches:
      - main
    paths:
      - api/*Dockerfile
      - docker/**

concurrency:
  group: api-docker-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  api-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          context: ./api
          file: ./api/poetry.Dockerfile
          platforms: ${{ matrix.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
