name: Run Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: sk-IamNotARealKeyJustForMockTestKawaiiiiiiiiii
      AZURE_OPENAI_API_BASE: https://difyai-openai.openai.azure.com
      AZURE_OPENAI_API_KEY: xxxxb1707exxxxxxxxxxaaxxxxxf94
      ANTHROPIC_API_KEY: sk-ant-api11-IamNotARealKeyJustForMockTestKawaiiiiiiiiii-NotBaka-ASkksz
      CHATGLM_API_BASE: http://a.abc.com:11451
      XINFERENCE_SERVER_URL: http://a.abc.com:11451
      XINFERENCE_GENERATION_MODEL_UID: generate
      XINFERENCE_CHAT_MODEL_UID: chat
      XINFERENCE_EMBEDDINGS_MODEL_UID: embedding
      XINFERENCE_RERANK_MODEL_UID: rerank
      GOOGLE_API_KEY: abcdefghijklmnopqrstuvwxyz
      HUGGINGFACE_API_KEY: hf-awuwuwuwuwuwuwuwuwuwuwuwuwuwuwuwuwu
      HUGGINGFACE_TEXT_GEN_ENDPOINT_URL: a
      HUGGINGFACE_TEXT2TEXT_GEN_ENDPOINT_URL: b
      HUGGINGFACE_EMBEDDINGS_ENDPOINT_URL: c
      MOCK_SWITCH: true
      CODE_MAX_STRING_LENGTH: 80000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install APT packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            ./api/requirements.txt
            ./api/requirements-dev.txt

      - name: Install dependencies
        run: pip install -r ./api/requirements.txt -r ./api/requirements-dev.txt

      - name: Run ModelRuntime
        run: pytest api/tests/integration_tests/model_runtime/anthropic api/tests/integration_tests/model_runtime/azure_openai api/tests/integration_tests/model_runtime/openai api/tests/integration_tests/model_runtime/chatglm api/tests/integration_tests/model_runtime/google api/tests/integration_tests/model_runtime/xinference api/tests/integration_tests/model_runtime/huggingface_hub/test_llm.py

      - name: Run Tool
        run: pytest api/tests/integration_tests/tools/test_all_provider.py

      - name: Run Workflow
        run: pytest api/tests/integration_tests/workflow
