name: Run Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - "3.10"
        os:
          # - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            ./api/requirements.txt
            ./api/requirements-dev.txt

      - name: Install dependencies
        run: pip install -r ./api/requirements.txt -r ./api/requirements-dev.txt

      - uses: msys2/setup-msys2@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          install: >-
            curl
            git
            bash

      - name: Run Unit tests
        run: bash dev/pytest/pytest_unit_tests.sh

      - name: Run ModelRuntime
        # if: ${{ matrix.os != 'windows-latest' }}
        run: bash dev/pytest/pytest_model_runtime.sh

      - name: Run Tool
        run: bash dev/pytest/pytest_tools.sh

      - name: Set up Sandbox
        uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          compose-file: |
            docker/docker-compose.middleware.yaml
          services: |
            sandbox

      - name: Run Workflow
        run: bash dev/pytest/pytest_workflow.sh

      - name: Set up Vector Stores (Weaviate, Qdrant, Milvus, PgVecto-RS)
        uses: hoverkraft-tech/compose-action@v2.0.0
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          compose-file: |
            docker/docker-compose.middleware.yaml
            docker/docker-compose.qdrant.yaml
            docker/docker-compose.milvus.yaml
            docker/docker-compose.pgvecto-rs.yaml
          services: |
            weaviate
            qdrant
            etcd
            minio
            milvus-standalone
            pgvecto-rs

      - name: Test Vector Stores
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: dev/pytest/pytest_vdb.sh
